---
stages:
    - infrastructure-update

variables:
    PULUMI_STACK: digitalocean

default:
    image: pulumi/pulumi-python:latest

pulumi:
    stage: infrastructure-update
    before_script:
        - pip install -r requirements.txt
        - pulumi stack select $PULUMI_STACK        
    script:
        - pulumi preview
    artifacts:
        paths:
            - pulumi-log.txt
        expire_in: 1 week
    only:
        - main

pulumi-preview:
    stage: infrastructure-update
    before_script:
        - pip install -r requirements.txt
        - pulumi stack select $PULUMI_STACK
    script:
        - pulumi preview
    only:
        - merge_requests