---
stages:
    - infrastructure-update

variables:
    PULUMI_STACK: digitalocean

default:
    image: pulumi/pulumi:latest

pulumi:
    stage: infrastructure-update
    before_script:
        - chmod +x ./.scripts/*.sh
        - ./.scripts/setup.sh
    script:
        - ./.scripts/run-pulumi.sh
    artifacts:
        paths:
            - pulumi-log.txt
        expire_in: 1 week
    only:
        - main

pulumi-preview:
    stage: infrastructure-update
    before_script:
        - chmod +x ./.scripts/*.sh
        - ./.scripts/setup.sh
    script:
        - ./.scripts/pulumi-preview.sh
    only:
        - merge_requests